<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<ApplicationIcon>Asset\icono_inventario.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Asset\logo_gad.png" />
    <None Remove="login_illustration.jpeg" />
    <None Remove="Logo.jpeg" />
    <None Remove="logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" Version="2026.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventarioSimple\InventarioSimple.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Asset\logo_gad.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="login_illustration.jpeg" />
    <Resource Include="logo.png" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="Asset\icono_inventario.ico" />
	</ItemGroup>

</Project>
